let suggestions = [
    "Amazon",
    "Best Buy",
    "ChatGPT",
    "YouTube",
    "ChatGPT",
    "eBay",
    "Blogger",
    "Facebook",
    "Google Maps",
    "HelloFresh",
    "Instagram",
    "Kayak",
    "McAfee",
    "Designer",
    "Developer",
    "Netflix",
    "Web Developer",
    "Opera",
    "Quest Diagnostics",
    "How to learn JavaScript",
    "Spotify",
];